# Generated by Django 3.0.2 on 2020-01-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transationid', models.CharField(max_length=20)),
                ('timestamp', models.TimeField()),
                ('projectid', models.CharField(max_length=20)),
                ('siteid', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('debitaccountid', models.CharField(max_length=20)),
                ('creditaccountid', models.CharField(max_length=20)),
                ('issuer', models.CharField(max_length=20)),
                ('reciverid', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=20)),
                ('resontype', models.CharField(max_length=20)),
                ('payflag', models.BooleanField()),
            ],
        ),
    ]
