# Generated by Django 3.0.2 on 2020-02-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='name',
        ),
        migrations.AddField(
            model_name='shift',
            name='break1end',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='shift',
            name='break1start',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='shift',
            name='break2end',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='shift',
            name='break2start',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='shift',
            name='lunchbreakend',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='shift',
            name='lunchbreakstart',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='shift',
            name='shiftend',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='shift',
            name='shiftstart',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
