# Generated by Django 3.0.2 on 2020-02-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_auto_20200213_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='break1end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='break1start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='break2end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='break2start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='lunchbreakend',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='lunchbreakstart',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shiftend',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shiftstart',
            field=models.TimeField(),
        ),
    ]
