# Generated by Django 3.0.2 on 2020-02-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0004_shift_siteclosetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='shiftId',
            field=models.CharField(default='123AWEFGGFRE', max_length=50),
            preserve_default=False,
        ),
    ]
