# Generated by Django 3.0.2 on 2020-01-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transationid', models.CharField(max_length=50)),
                ('timestamp', models.TimeField()),
                ('projectid', models.CharField(max_length=50)),
                ('siteid', models.CharField(max_length=50)),
                ('creditaccountid', models.CharField(max_length=50)),
                ('debitaccountid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='accountinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labourerid', models.CharField(max_length=50)),
                ('timestamp', models.TimeField()),
                ('phonenumber', models.CharField(max_length=20)),
                ('siteid', models.CharField(max_length=50)),
                ('recoveryperiod', models.CharField(max_length=50)),
                ('reson', models.CharField(max_length=150)),
                ('approveid', models.CharField(max_length=50)),
                ('approvestatus', models.BooleanField()),
                ('paystatus', models.BooleanField()),
            ],
        ),
    ]
