# Generated by Django 3.0.2 on 2020-01-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='labourerclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labourerclass', models.CharField(max_length=50)),
                ('wageclass', models.CharField(max_length=50)),
                ('labourerclassid', models.CharField(max_length=50)),
                ('compensation', models.BooleanField()),
                ('retention', models.BooleanField()),
                ('advance', models.BooleanField()),
                ('concretecharges', models.BooleanField()),
            ],
        ),
    ]
