# Generated by Django 3.0.2 on 2020-01-28 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=100)),
                ('numberOflabourer', models.IntegerField()),
                ('compensationamount', models.IntegerField()),
                ('compensationdays', models.IntegerField()),
                ('concreteamount', models.IntegerField()),
                ('creditaccountid', models.CharField(max_length=20)),
                ('debitaccountid', models.CharField(max_length=20)),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanage.project')),
            ],
        ),
    ]
