# Generated by Django 3.0.2 on 2020-01-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendanceManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('labourerid', models.CharField(max_length=50)),
                ('labourername', models.CharField(max_length=50)),
                ('labourerclass', models.CharField(max_length=50)),
                ('shiftid', models.CharField(max_length=50)),
                ('labouercategory', models.CharField(max_length=50)),
                ('labourertype', models.CharField(max_length=50)),
                ('intime', models.TimeField()),
                ('outtime', models.TimeField()),
                ('numberofhours', models.IntegerField()),
                ('overtimeallocated', models.BooleanField()),
                ('overtimeworked', models.BooleanField()),
                ('siteid', models.CharField(max_length=50)),
                ('projectid', models.CharField(max_length=50)),
            ],
        ),
    ]
