# Generated by Django 3.0.2 on 2020-02-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lbourWorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('intime', models.TimeField()),
                ('outtime', models.TimeField()),
                ('otStart', models.TimeField()),
                ('otEnd', models.TimeField()),
            ],
        ),
    ]
