# Generated by Django 3.0.2 on 2020-02-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManage', '0003_lbourworktime_labourerid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lbourWorkTime',
            new_name='labourWorkTime',
        ),
    ]
