# Generated by Django 3.0.2 on 2020-02-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManage', '0005_auto_20200213_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancemanage',
            name='intime',
        ),
        migrations.RemoveField(
            model_name='attendancemanage',
            name='outtime',
        ),
    ]
