# Generated by Django 3.0.2 on 2020-02-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManage', '0006_auto_20200213_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancemanage',
            name='shiftid',
        ),
        migrations.RemoveField(
            model_name='attendancemanage',
            name='siteid',
        ),
        migrations.AddField(
            model_name='labourworktime',
            name='otstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labourworktime',
            name='shiftid',
            field=models.CharField(default=1231, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labourworktime',
            name='siteid',
            field=models.CharField(default=123213, max_length=50),
            preserve_default=False,
        ),
    ]
