# Generated by Django 3.0.2 on 2020-02-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManage', '0007_auto_20200214_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourworktime',
            name='outtime',
            field=models.TimeField(null=True),
        ),
    ]
