# Generated by Django 3.0.2 on 2020-02-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManage', '0009_auto_20200214_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labourworktime',
            old_name='otEnd',
            new_name='othours',
        ),
        migrations.RemoveField(
            model_name='labourworktime',
            name='otStart',
        ),
        migrations.AlterField(
            model_name='labourworktime',
            name='labourerid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
