# Generated by Django 3.0.2 on 2020-02-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManage', '0010_auto_20200214_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labourworktime',
            old_name='othours',
            new_name='otEnd',
        ),
        migrations.AddField(
            model_name='labourworktime',
            name='otStart',
            field=models.TimeField(null=True),
        ),
    ]
