# Generated by Django 3.0.2 on 2020-02-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManage', '0011_auto_20200214_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labourworktime',
            old_name='otEnd',
            new_name='othours',
        ),
        migrations.RemoveField(
            model_name='labourworktime',
            name='otStart',
        ),
    ]
