# Generated by Django 3.0.2 on 2020-02-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabourerManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labourerid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='pics')),
                ('aadharNumber', models.CharField(max_length=50)),
                ('aadhrPhoto', models.ImageField(blank=True, upload_to='Aadharpics')),
                ('fatherName', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('bankName', models.CharField(max_length=50)),
                ('ACNumber', models.CharField(max_length=50)),
                ('branchName', models.CharField(max_length=50)),
                ('IFSCNumber', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('bloodGroup', models.CharField(max_length=50)),
                ('employeeCode', models.CharField(max_length=50)),
                ('salaryStructure', models.CharField(max_length=50)),
                ('labourerType', models.CharField(max_length=50)),
                ('skillType', models.CharField(max_length=50)),
            ],
        ),
    ]
