# Generated by Django 3.0.2 on 2020-01-28 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personal_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lbourerName', models.CharField(max_length=100)),
                ('callByName', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('dateOfBirth', models.DateField()),
                ('fatherName', models.CharField(max_length=100)),
                ('bloodGroup', models.CharField(choices=[('A+', 'A+'), ('A1+', 'A1+'), ('B+', 'B+'), ('O+', 'O+'), ('O-', 'O-'), ('A-', 'A-'), ('B-', 'B-')], max_length=10)),
                ('NxtOFKin', models.CharField(max_length=12)),
                ('contactNumOfNxtOfKin', models.CharField(max_length=12)),
                ('motherTounge', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pinCode', models.CharField(max_length=20)),
                ('mobileNUmber', models.CharField(max_length=12)),
                ('residencePHNumber', models.CharField(max_length=12)),
                ('emergencyPHNumber', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='identity_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentType', models.CharField(max_length=50)),
                ('documentNumber', models.CharField(max_length=50)),
                ('nameAsPerTheDocument', models.CharField(max_length=100)),
                ('labourerid', models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='labourer.personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='employeement_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfJoining', models.DateField()),
                ('migrateWoker', models.BooleanField()),
                ('designation', models.CharField(max_length=20)),
                ('projectNeme', models.CharField(max_length=50)),
                ('siteName', models.CharField(max_length=50)),
                ('siteID', models.CharField(max_length=50)),
                ('siteOfJoining', models.CharField(max_length=50)),
                ('labourerid', models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='labourer.personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='bankAccount_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BankName', models.CharField(max_length=50)),
                ('ifscCode', models.CharField(max_length=50)),
                ('branchName', models.CharField(max_length=50)),
                ('bankAccountNumber', models.CharField(max_length=50)),
                ('nameinBank', models.CharField(max_length=50)),
                ('labourerid', models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='labourer.personal_info')),
            ],
        ),
    ]
