# Generated by Django 3.0.2 on 2020-01-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labourer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeement_info',
            name='labouerGrade',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='employeement_info',
            name='labouerGraderatio',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeement_info',
            name='labourerType',
            field=models.CharField(default='union', max_length=50),
            preserve_default=False,
        ),
    ]
