# Generated by Django 3.0.2 on 2020-02-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteid', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('clientName', models.CharField(blank=True, max_length=50, null=True)),
                ('projectIncharge', models.CharField(blank=True, max_length=50, null=True)),
                ('typeOfProject', models.CharField(blank=True, max_length=50, null=True)),
                ('siteEngineer', models.CharField(blank=True, max_length=50, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('lunchTime', models.TimeField(blank=True, null=True)),
                ('startTime', models.TimeField(blank=True, null=True)),
                ('endTime', models.TimeField(blank=True, null=True)),
                ('strtBuffer', models.TimeField(blank=True, null=True)),
                ('endBuffer', models.TimeField(blank=True, null=True)),
                ('salaryStructure', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
